export const APP_VERSION = "v.02.46.12";
export const VERSION_DATE = "2026-06-12";
export const VERSION_CHANGELOG = [
  "v.02.46.12 - Feat: Novos campos de valor contratual na aba Info Pessoal da Ficha do Colaborador: Conectividade (auxílio conectividade) e Incentivos. Valores inclusos no cálculo do Total Geral de Remuneração. Armazenados via metadata no banco sem alteração de schema.",
  "v.02.46.10 - Fix: Remove 'Início do ciclo' do cabeçalho do card de contrato; adiciona regra obrigatória de version bump no GEMINI.md.",
  "v.02.46.09 - Feat: Campo 'Vencimento da 1ª Parcela' obrigatório no cadastro de empréstimo; exibe 'Início do débito' no card do contrato.",
  "v.02.46.08 - Feat: Empréstimos — edição de datas contratuais (assinatura e 1ª parcela), botão de baixa manual por parcela, cálculo de saldo devedor baseado em status real do banco, travamento de edição após 1º pagamento, liquidação correta de todas as parcelas via botão Liquidar, e UX otimizada do drawer sem reload visual.",
  "v.02.46.07 - Fix: Remove systemInstruction param from Gemini model due to compatibility issues with standard prompts and display early errors.",
  "v.02.46.06 - Fix: Adiciona gemini-1.0-pro e forca cache invalidation para resolver 404 da API do Gemini.",
  "v.02.46.05 - Feat: Criação do Importador Inteligente (Data Lake Dianna) na aba Custo Histórico, permitindo buscar registros diretamente da planilha bruta e importar em lote de forma visual e seletiva.",
  "v.02.46.04 - Feat: Novo visual para os alertas de auditoria (transformados em Cards KPI) com navegação fluída, e melhoria na regra de alertas de admissão vs custo de folha (não gera alerta no mês da admissão).",
  "v.02.46.03 - Feat: Separação do Valor Base e Bônus na listagem e também dentro do detalhamento de Custo de Folha, com a remoção da coluna Aditivos.",
  "v.02.46.01 - Feat: Nomenclatura dinâmica e inteligente para documentos processados por IA. Agora o sistema extrai o título exato do documento (ex: 'CONTRATO PRESTAÇÃO DE SERVIÇO'), identifica sobre o que é o aditivo (ex: 'Aditivo (Mudança de Função)') e usa a data da assinatura ao invés da data de upload.",
  "v.02.46.00 - Feat: Trajetória Profissional aprimorada como um Dossiê Dinâmico. Agora a IA detecta Distratos automaticamente, encerra o contrato e altera o status. A linha do tempo exibe Contratos, Aditivos e Rescisões com botões para abrir os respectivos documentos atrelados a cada evento.",
  "v.02.45.23 - Fix: Reversão da exclusão em cascata. Históricos financeiros e de contratos serão sempre mantidos. Exclusão agora restrita apenas a cadastros sem histórico.",
  "v.02.45.22 - Fix: Exclusão de colaboradores agora limpa manualmente todas as tabelas dependentes (empréstimos, aditivos, custos e histórico) contornando a falta de ON DELETE CASCADE no banco de dados.",
  "v.02.45.21 - Fix: Mapeamento de metadata (grau, glosa, e last_raise_date) na listagem principal do dashboard que estava sendo ignorado.",
  "v.02.45.20 - Feat: Adição do campo Grau, opções de filtro de Grau (I, II, III padronizados), e upload simplificado na criação.",
  "v.02.45.19 - Fix: Removido vínculo MEI (mantido apenas em Regime Tributário), adição de checkboxes com seleção múltipla para todos os filtros do dashboard, correção do card Saldo Devedor para reagir em tempo real aos filtros, e bypass do bucket de fotos para usar o diretório /avatars do bucket contracts.",
  "v.02.45.18 - Feat: Upload de foto de perfil via Supabase Storage, atalho de empréstimos na ficha, painel de auditoria clicável com detalhes de ocorrências, listagem detalhada de devedores no painel de KPIs, cards executivos reativos aos filtros da tabela e remoção do código de país (+55) na extração da IA.",
  "v.02.45.17 - Feat: Mapeamento de vencimento de contratos e aditivoCount na listagem principal de People Board; normalização e prevenção de duplicidades fonéticas/ortográficas em locais de prestação (trim e capitalize); botão de busca e vinculação de colaboradores cadastrados na criação para evitar cadastros duplicados; extração automática de bônus por IA do contrato priorizando o maior valor.",
  "v.02.45.16 - Fix: constraint employees_company_check agora inclui G2; busca de colaborador existente agora verifica coluna 'name' além de 'full_name'; campo Nível (Estratégico/Tático/Operacional) adicionado; Comissão alterada para selecionável por plano; Setor/Função com data de início e histórico; Local de Prestação com autocomplete do DB; novos campos nivel/commission_plan/department_start_date adicionados ao Employee type e mappers.",
  "v.02.45.13 - Feat: Máscaras de telefone pessoal e CNPJ, campos profissionais (telefone/email) no Info Pessoal com máscaras, validações matemáticas de CPF/CNPJ (dígitos verificadores), tratamento de erros e suporte a contratos de qualquer tamanho (>4.5MB) utilizando upload prévio para o storage e posterior leitura por IA.",
  "v.02.45.12 - Fix: Confirmação ao fechar ficha em modo de edição, bloqueio de fechar com clique fora e upload automático do PDF do contrato para o Supabase Storage com vínculo de aditivo.",
  "v.02.45.11 - Feat: Habilitação de importação de dados por upload de PDF de contrato (utilizando IA Gemini 1.5 Flash para auto-preenchimento) e desativação de clique-fora para fechar o modal em modo de edição.",
  "v.02.45.10 - Fix: Máscara e validação no campo CPF (máximo 11 dígitos, bloqueando CNPJ) e prevenção de fechamento automático do modal (ProfileDrawer) por propagação de clique.",
  "v.02.45.9 - Feat: Reestruturação do Cadastro Único (PeopleBoard) com novos campos, abas, filtros (Terceirização, Local, Regime Tributário) e limpeza do DB.",
  "v.02.45.8 - Fix: Busca automática de CEP ao digitar, máscara e loader visual de progresso.",
  "v.02.45.7 - Feat: Mudar título para PeopleBoard e mover a exibição da versão abaixo do título da barra lateral.",
  "v.02.45.6 - Feat: Ampliação das fontes, cabeçalhos, crachás e detalhes em todas as demais abas da Ficha do Colaborador (Dados Auxiliares, Trajetória, Custos, Auditoria).",
  "v.02.45.5 - Fix: Refatoração do dynamic require do pdf.service para import() dinâmico assíncrono eliminando alertas do linter.",
  "v.02.45.4 - Feat: Centralização da Ficha do Colaborador (Modal) com fontes e paddings ampliados para melhor legibilidade.",
  "v.02.45.3 - Feat: Geração da planilha unificada Dados_Consolidados_RH.xlsx contendo dados do Supabase e da planilha Dianna para limpeza.",
  "v.02.45.2 - Fix: Mapeamento de datas de admissão e desligamento e tratamento de data vazia (convertendo string vazia para null) ao salvar.",
  "v.02.45.1 - Fix: Correção crítica de colunas SQL e mapeamento de dados dos colaboradores no cockpit.",
  "v.02.45.0 - Feat: Nova versão renomeada para forçar atualização de cache e verificação do deploy.",
  "v.02.44.0 - Feat: Segregação completa de empréstimos na página People e criação do gráfico de folha Dianna.",
  "v.02.43.0 - Fix: Resolvido erro de compilação no Vercel adicionando o export faltante DEFAULT_DRE_ESTRUTURA no dre.service.ts.",
  "v.02.42.0 - Fix: Aplicação final da injeção do template DRE (DEFAULT_DRE_ESTRUTURA) na página.",
  "v.02.41.0 - Fix: Resolvido erro crítico no brisinhai.js (isResizing) que travava a execução do JavaScript.",
  "v.02.40.0 - Fix: Estrutura DRE inlinada no serviço — elimina falha silenciosa de fetch do template JSON.",
  "v.02.39.0 - Fix: DRE CSV agora parseado corretamente com delimitador ponto-e-vírgula (;) padrão BR.",
  "v.02.38.0 - Fix: Cadeia de fallback completa para resolver fornecedor em CP, CR e MOVIMENTO.",
];
